# Generated by Django 5.2.1 on 2025-05-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1024, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('delay', models.IntegerField(choices=[(0, 'Без задержки'), (1, 'Через 1 час'), (2, 'Через 1 день')], default=0, verbose_name='Задержка')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес получателя')),
                ('is_telegram', models.BooleanField(default=False, verbose_name='Телеграм')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Успешно'), ('failed', 'Неудачно')], default='pending', max_length=10, verbose_name='Статус')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification', verbose_name='Уведомление')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.recipient', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Лог отправки',
                'verbose_name_plural': 'Логи отправки',
            },
        ),
    ]
